// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGCxR7de8_3zCE7dS0khaH7FEb8apReRI',
    appId: '1:190673551377:web:55594db3fc95b48f14f1b0',
    messagingSenderId: '190673551377',
    projectId: 'apple-store-sl',
    authDomain: 'apple-store-sl.firebaseapp.com',
    storageBucket: 'apple-store-sl.appspot.com',
    measurementId: 'G-0431ETFWYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmAI6jRVDA5lrAyuIBe4jXubKaunYE5Ag',
    appId: '1:190673551377:android:1852b8c4b3f75bcc14f1b0',
    messagingSenderId: '190673551377',
    projectId: 'apple-store-sl',
    storageBucket: 'apple-store-sl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9GOmeC6VpYGqXrtchuYpc8YjbpA0DlBs',
    appId: '1:190673551377:ios:b9faa38251dc653a14f1b0',
    messagingSenderId: '190673551377',
    projectId: 'apple-store-sl',
    storageBucket: 'apple-store-sl.appspot.com',
    iosBundleId: 'lk.ce.apple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9GOmeC6VpYGqXrtchuYpc8YjbpA0DlBs',
    appId: '1:190673551377:ios:b9faa38251dc653a14f1b0',
    messagingSenderId: '190673551377',
    projectId: 'apple-store-sl',
    storageBucket: 'apple-store-sl.appspot.com',
    iosBundleId: 'lk.ce.apple',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGCxR7de8_3zCE7dS0khaH7FEb8apReRI',
    appId: '1:190673551377:web:58b1f12da8f1652214f1b0',
    messagingSenderId: '190673551377',
    projectId: 'apple-store-sl',
    authDomain: 'apple-store-sl.firebaseapp.com',
    storageBucket: 'apple-store-sl.appspot.com',
    measurementId: 'G-V7WXF4ZFRK',
  );
}
